@startuml
'https://plantuml.com/component-diagram


package "G16" {
  package "Controllers"
  package "Dev"
  package "Fields"{
  package BuyableFields
  package UnbuyableFields
  }
  package Graphics
  package PlayerUtils
}


@enduml