@startuml
title Activity diagram

start
:Choose language input;
:Create players;
:Fill in player's name;
:Throw dice;

if (Land on Fields) then
'
  if (BuyableFields) is (yes) then
    :No owner;
    if (Purchase?) is (yes) then
      :Buy property;
    else (no)
      :Other players can make an offer;
    endif

   else (no))
        if (Has owner?) then
          if (Their own land?) is (yes) then
            :true;
          else (no)
            :Pay rent;
          endif
        else
          :false;
        endif
  endif

else
  if (UnbuyableFields) then
    if (Go to Jail) then
        if ("Thow dice 3 times?") is (yes) then
        :Release;
        '--> Release
        else (no)
        :Stay in jail;
        endif
    else
    :Pay 1000kr.;
    endif
   else
    :Chance cards;
endif



@enduml